B28G10_97_Ahmad
Pahirdin/CRM_Canis_Project pull request #34
Opened 2023-03-09 22:15 UTC by Kiomarz

2023-03-09 22:17 UTC, ivannakravtsiv approved these changes

2023-03-09 23:33 UTC, marick777 requested changes
in CukesRunner you have to remove your tag, before push it to master

2023-03-09 23:33 UTC, marick777 commented on src/test/java/com/canis/runners/CukesRunner.java
> +        tags = "@B28G10-153",
you have to remove your tag, before push it to master

2023-03-10 01:34 UTC, Pahirdin approved these changes

2023-03-10 01:35 UTC, merged